# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/main/json-schema/pinact.json
version: 3

files:
  - pattern: ".github/workflows/*.yml"
  - pattern: ".github/actions/*/action.yml"

ignore_actions:
  - name: voicevox/merge-gatekeeper
    ref: main

rules:
  - ignore: true
    conditions:
      - expr: |
          ActionName == "pypa/gh-action-pip-audit" && ActionVersion == "aad10797d60f7c941f2c511ffb70fd81d998c2a2"
