# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pysen-lint
        name: pysen-lint
        entry: poetry run pysen run lint
        language: system
        types: [file, python]
        stages: [push]
        pass_filenames: false
      - id: poetry-check # `pyproject.toml` と `poetry.lock` が整合する
        name: poetry-check
        entry: poetry check
        language: python
        stages: [push]
        pass_filenames: false
      - id: update-licenses
        name: update-licenses
        entry: poetry run task update-licenses
        language: system
        stages: [push]
        pass_filenames: false
