# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]
ba="ba" # 7zコマンドの-baオプション
datas="datas" # PyInstallerの引数

[files]
extend-exclude = ["dictionaries", "engine_manifest_assets", "poetry.*", "requirements*.txt"]
