# typos の設定ファイル
# 書式は以下の公式ドキュメントを参照: https://github.com/crate-ci/typos#false-positives

[default.extend-words]
datas="datas" # PyInstallerの引数

[files]
extend-exclude = [
    "resources",
    "test/e2e/single_api/engine_info/__snapshots__/test_engine_manifest/test_get_engine_manifest_200.json",
    "poetry.*",
    "requirements*.txt",
]
