name: Build Docker
on:
  push:
    branches:
      - master
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      version:
        description: "バージョン情報（A.BB.C / A.BB.C-preview.D）"
        required: true

env:
  PYTHON_VERSION: "3.11.9"
  IMAGE_NAME: ghcr.io/aivis-project/aivisspeech-engine

defaults:
  run:
    shell: bash

jobs:
  config: # 全 jobs で利用する定数の定義. `env` が利用できないコンテキストでも利用できる.
    runs-on: ubuntu-latest
    outputs:
      version_or_latest: ${{ steps.vars.outputs.version_or_latest }}
    steps:
      - name: <Setup> Declare variables
        id: vars
        run: |
          : # releaseタグ名か、workflow_dispatchでのバージョン名か、latestが入る
          echo "version_or_latest=${{ github.event.release.tag_name || github.event.inputs.version || 'latest' }}" >> "$GITHUB_OUTPUT"

  build-docker:
    needs: [config]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        tag:
          - ""
          - cpu
          - nvidia
        include:
          # Ubuntu 20.04
          - tag: ""
            target: runtime-env
            base_image: ubuntu:20.04
            base_runtime_image: ubuntu:20.04
            platforms: linux/amd64,linux/arm64/v8
          - tag: cpu
            target: runtime-env
            base_image: ubuntu:20.04
            base_runtime_image: ubuntu:20.04
            platforms: linux/amd64,linux/arm64/v8
          - tag: nvidia
            target: runtime-nvidia-env
            base_image: ubuntu:20.04
            base_runtime_image: nvidia/cuda:12.6.2-cudnn-runtime-ubuntu20.04
            platforms: linux/amd64

    steps:
      - name: <Setup> Check out the repository
        uses: actions/checkout@v4

      - name: <Setup> Prepare Python version
        id: prepare-python
        uses: ./.github/actions/prepare_python
        with:
          only-export-python-version: true

      - name: <Setup> Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: <Setup> Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: <Setup> Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: <Build/Deploy> Build and Deploy Docker image
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG:
            |- # If it's a release, add the version, otherwise add the `latest`
            ${{ (
              matrix.tag != '' && (
                format('{0}:{1}-{2}', env.IMAGE_NAME, matrix.tag, needs.config.outputs.version_or_latest)
              ) || format('{0}:{1}', env.IMAGE_NAME, needs.config.outputs.version_or_latest)
            ) }}
          IMAGE_CACHE_FROM:
            |- # Always use the `latest` buildcache. :latest-buildcache or :{tag}-latest-buildcache
            ${{ (
              matrix.tag != '' && (
                format('type=registry,ref={0}:{1}-latest-buildcache', env.IMAGE_NAME, matrix.tag)
              ) || format('type=registry,ref={0}:latest-buildcache', env.IMAGE_NAME)
            ) }}
          IMAGE_CACHE_TO:
            |- # If it's a release, do not create buildcache, otherwise create the `latest` buildcache. :latest-buildcache or :{tag}-latest-buildcache
            ${{ (
              needs.config.outputs.version_or_latest == 'latest' && (
                matrix.tag != '' && (
                  format('type=registry,ref={0}:{1}-latest-buildcache,mode=max', env.IMAGE_NAME, matrix.tag)
                ) || format('type=registry,ref={0}:latest-buildcache,mode=max', env.IMAGE_NAME)
              ) || ''
            ) }}
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            BASE_RUNTIME_IMAGE=${{ matrix.base_runtime_image }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            AIVISSPEECH_ENGINE_VERSION=${{ needs.config.outputs.version_or_latest }}
          target: ${{ matrix.target }}
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: ${{ env.IMAGE_CACHE_FROM }}
          cache-to: ${{ env.IMAGE_CACHE_TO }}
          platforms: ${{ matrix.platforms }}

  run-release-test-workflow:
    # version が指定されている場合のみ実行する
    if: needs.config.outputs.version_or_latest != 'latest'
    needs: [config, build-docker]
    uses: ./.github/workflows/test-engine-container.yml
    with:
      version: ${{ needs.config.outputs.version_or_latest }}
      repo_url: ${{ format('{0}/{1}', github.server_url, github.repository) }} # このリポジトリのURL
